language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run test
  - npm run build
before_deploy:
  - yarn global add travis-ci-cloudfront-invalidation
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  google_maps_api_key: $GOOGLE_MAPS_API_KEY
  skip_cleanup: true
  local-dir: dist
  on:
    branch: master
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
